Import( 'context' )

env = Environment()

env.Append(CCFLAGS = ['-m64'])
env.Append(CCFLAGS = ['-std=c++0x'])

env.Append(LIBS = ['GL', 'GLU'])

sources = [ 'Addin.cpp', 'SimpleRenderer.cpp' ]

env.SharedLibrary(target='simplerenderer', source=sources)

info = File('SimpleRenderer.xml')
Command(info, info.srcnode(), Copy('$TARGET', '$SOURCE'))
