Import( 'context' )

env = Environment()

env.Append(CCFLAGS = ['-m64'])
env.Append(CCFLAGS = ['-std=c++0x'])
env.Append(LINKFLAGS = [ '-rdynamic' ])

env.Append(LIBS = ['vulkan', 'xerces-c-3.1', 'v8', 'pthread', 'GL', 'X11', 'Xxf86vm', 'dl'])

sources = [ 'Main.cpp', 'Engine.cpp', 'EngineConfig.cpp', 'AddinInfo.cpp', 'AddinContainer.cpp', 'Log.cpp' ]

lib_sources = [ 'XercesUtils.cpp' ]
sources[len(sources):] = context.BuildSourceList('lib', lib_sources)

platform_sources = [ 'PlatformConfig.cpp' ]
sources[len(sources):] = context.BuildSourceList('platform', platform_sources)

linux_sources = [ 'X11Vulkan.cpp', 'X11Config.cpp' ]
sources[len(sources):] = context.BuildSourceList('platform/x11', linux_sources)

scripting_sources = [ 'Script.cpp', 'ScriptContext.cpp', 'ScriptUtil.cpp' ]
sources[len(sources):] = context.BuildSourceList('scripting', scripting_sources)

framework_sources = [ 'Game.cpp', 'GameComponent.cpp', 'GameObject.cpp' ]
sources[len(sources):] = context.BuildSourceList('framework', framework_sources)

env.Program(target='game', source=sources)
